import logging
from typing import Dict, Any, Set
from ragpipe.domain.models.media import MediaType, Song, Podcast, Video, MediaItem
from ragpipe.domain.models.modality import Modality, ModalityStatus
from ragpipe.domain.ports.media_repository import MediaRepository
from ragpipe.domain.ports.vector_repository import VectorRepository
from ragpipe.domain.ports.event_bus import EventBus

logger = logging.getLogger(__name__)

class RecoveryManager:
    """Service for recovering missing SQLite records from Qdrant vectors."""
    def __init__(self, vector_repository: VectorRepository, media_repository: MediaRepository, event_bus: EventBus):
        self.vector_repo = vector_repository
        self.media_repo = media_repository
        self.event_bus = event_bus

    async def run_recovery(self) -> Dict[str, Any]:
        """Scan all vector collections and recover missing MediaItems."""
        logger.info("Starting Qdrant -> SQLite data recovery scan...")
        
        try:
            collections = await self.vector_repo.list_collections()
        except Exception as e:
            logger.error(f"Failed to list collections for recovery: {e}")
            return {"status": "error", "message": "Vector DB unreachable"}
            
        recovered_count = 0
        processed_media_ids: Set[str] = set()
        
        for collection in collections:
            # We assume collection names are formatted like {modality}_{version_id}
            # though it doesn't strictly matter as long as payload has media_type and media_id
            offset = None
            while True:
                results, offset = await self.vector_repo.scroll(collection, limit=100, offset=offset)
                
                for res in results:
                    payload = res.get("payload") or {}
                    media_id = payload.get("media_id")
                    if not media_id or media_id in processed_media_ids:
                        continue
                        
                    # Check if it exists in local DB
                    existing_media = await self.media_repo.get(media_id)
                    if existing_media:
                        processed_media_ids.add(media_id)
                        continue
                        
                    # Missing in local DB, recover it!
                    await self._recover_media_item(media_id, payload)
                    recovered_count += 1
                    processed_media_ids.add(media_id)
                    
                if offset is None:
                    break
                    
        logger.info(f"Recovery complete. Recovered {recovered_count} media items.")
        return {"status": "success", "recovered_items": recovered_count}
        
    async def _recover_media_item(self, media_id: str, payload: dict):
        """Construct and save a MediaItem and its ModalityStatuses based on Qdrant payload."""
        media_type_str = payload.get("media_type", "song")
        
        # Build base fields from payload
        kwargs = {
            "title": payload.get("title", f"Recovered Item {media_id[:8]}"),
            "artist": payload.get("artist"),
            "album": payload.get("album"),
            "genre": payload.get("genre"),
            "tags": payload.get("tags", []),
            "duration": payload.get("duration"),
            "language": payload.get("language", "en"),
            "source_url": payload.get("source_url"),
        }
        
        # Determine media class and specific fields
        if media_type_str == MediaType.SONG.value:
            kwargs["bpm"] = payload.get("bpm")
            kwargs["key"] = payload.get("key")
            media_item = Song.create(**kwargs)
        elif media_type_str == MediaType.PODCAST.value:
            kwargs["show_name"] = payload.get("show_name")
            kwargs["episode_number"] = payload.get("episode_number")
            kwargs["host"] = payload.get("host")
            kwargs["guests"] = payload.get("guests", [])
            media_item = Podcast.create(**kwargs)
        elif media_type_str == MediaType.VIDEO.value:
            kwargs["resolution"] = payload.get("resolution")
            kwargs["fps"] = payload.get("fps")
            media_item = Video.create(**kwargs)
        else:
            # Fallback to Song if unknown
            media_item = Song.create(**kwargs)
            
        # Manually overwrite the ID generated by create() to match Qdrant's media_id
        import dataclasses
        media_item = dataclasses.replace(media_item, id=media_id)
        
        # Save media item
        await self.media_repo.save(media_item)
        
        # We don't know all modality statuses natively, but we can assume basic ones
        # and mark them as data_available=False by default (until proven otherwise by pipeline).
        # Actually, if it's in the DB, let's just initialize default empty statuses,
        # the system will let users re-upload or re-process.
        # But we could check which collection this came from...
        from ragpipe.domain.models.modality import ProcessingStatus
        from datetime import datetime, timezone
        
        for mod in Modality:
            status = ModalityStatus(
                media_id=media_id,
                modality=mod,
                data_available=False,
                embedding_status="pending",
                last_processed=None,
                error_message=None
            )
            await self.media_repo.save_modality_status(status)
            
        logger.info(f"Recovered media item: {media_id}")
